### ISSUE TITLE
Boggle might want a minor update

### ISSUE THREAD

**Issue by treeowl** [glguy/generic-traverse#1]
Now that `liftA2` is a method of `Applicative`, `Boggle` should probably use it in the underlying applicative wherever it would now use `fmap` with `<*>`. I don't know if `Boggle` could benefit from its own custom `liftA2`. I haven't read far enough to see, but I'm guessing no. One more thing: I see no support for using the underlying `<*`, `*>`, or `<$`.

**Comment by glguy** [comment]
This stack of operations is built around `<$>` and `<*>`. Another design could provide more support for `liftA2` or `<*` . At this point I think that plumbing those through might just interfere with the demonstrative purpose of the package.

**Comment by glguy** [comment]
I'm going to close this until there are some concrete changes to consider.
